### ISSUE TITLE
How about the performance of dispatcher? 中心分发器的性能如何？

### ISSUE THREAD

**Issue by xiaonanln** [xiaonanln/goworld#15]
在一个典型的MMORPG里，能支持多少人同时在线？

**Comment by xiaonanln** [comment]
目前看来非常好

**Comment by xuxbuptisc** [comment]
目标不能是几万人吧。理论上可以设计成无限水平扩展，全球同服，为啥要自己限制自己。gate和game直连也没有什么问题啊。

**Comment by xiaonanln** [comment]
你说的有道理，接下来的一个任务是采用dispatcher shard的方式让dispatcher也实现分布式

**Comment by xuxbuptisc** [comment]
感觉没有必要用dispatcher转发呀，还多走一条转发链路，如果只是为了保证migrate的时序性，感觉可以仔细考虑下是否可以别的实现方式。从dispatcher走直觉上就很冗余，当作集群的控制中心用就可以了。
