### ISSUE TITLE
Support Google Protobuf 支持protobuf

### ISSUE THREAD

**Issue by xiaonanln** [xiaonanln/goworld#23]

**Comment by luochuanyuewu** [comment]
期待这个功能。

**Comment by docall** [comment]
现在用的什么序列化？

**Comment by xiaonanln** [comment]
MessagePack

**Comment by magix** [comment]
这样确实 很好。尤其是做大并发，可以做棋牌有点麻烦，因为格式比较乱一些。没有想网游那么简单。

**Comment by bytemode** [comment]
期待支持google protobuf

**Comment by fnaith** [comment]
從開 Issue 到現在也有點時間了，如果還有要做的話，或許可以考慮改成 [Flatbuffers](https://google.github.io/flatbuffers/) 了XD

**Comment by xiaonanln** [comment]
Won't be implemented because it could involve large refactoring.
