### ISSUE TITLE
v0.1

### ISSUE THREAD

**Issue by xiaonanln** [xiaonanln/goworld#42]
Version v0.1
- Basic functionalities: entity, attributes, 
- TCP, KCP, WEBSOCKET
- Reload
- ext: db/gwmongo, pubsub, msgbox
- strip useless code

**Comment by luochuanyuewu** [comment]
作者开发很积极啊.. 居然才0.1版本。 期待1.0

**Comment by SonarBeserk** [comment]
Do you plan to remove the use of python? You should be able to do everything around process creation in go instead.

**Comment by xiaonanln** [comment]
good suggestion for removing python.

**Comment by SonarBeserk** [comment]
How close is v0.1 now?
