### ISSUE TITLE
[unity-demo] Player position not getting set on the server

### ISSUE THREAD

**Issue by spaceemotion** [xiaonanln/goworld#50]
I tried running the unity demo today and it works fine until it doesn't: The player positions does not seem to sync with the server quite right. The packet arrives, but at the wrong entity.

Somehow during the lifecycle the `entity.syncingFromClient` property is returning false as the player entity changes (even though the ID stays the same). Furthermore, the player entity seems to get added twice, which probably means we load the same player twice, but don't initialize them correctly - and thus overwrite the existing copy since it's a map.

**Comment by xiaonanln** [comment]
What you see wrong in the behavior of game characters?

**Comment by spaceemotion** [comment]
The player character can move around in the scene, but the server thinks they're still at 0,0,0. The monsters will target the player, but get all stuck at the same spot (0,0,0) as they think that's where the player is.

**Comment by xiaonanln** [comment]
Seems it is due to that entity.syncingFromClient is set to false. When entity.syncingFromClient is False, entity positions sent by client are simply ignored by server. Player normally set syncingFromClient=false when it is dead or in some unmovable states. Maybe some logic is invalid and set syncingFromClient=false incorrectly.

**Comment by spaceemotion** [comment]
Already checked that, it's not getting set anywhere except in the player initialization

**Comment by SonarBeserk** [comment]
Is it possible the entity for the player is being added to the entity map twice? You store an id mapped to an entity pointer and could possibly be adding an entity without the default attributes.

**Comment by xiaonanln** [comment]
should be fixed now

**Comment by xiaonanln** [comment]
this bug is because entity.syncingFromClient is reset to false after EnterSpace.
