### ISSUE TITLE
Architecture Image is a 404

### ISSUE THREAD

**Issue by SonarBeserk** [xiaonanln/goworld#51]
The architecture image in the readme is a dead link.

**Comment by xiaonanln** [comment]
should not be! Are you sure ?

**Comment by SonarBeserk** [comment]
Checking it again it just says "goworld architecture" and goes to a dead
page

**Comment by xiaonanln** [comment]
fixed now

**Comment by xiaonanln** [comment]
thanks very much for your issue.
