### ISSUE TITLE
属性同步代码实现是哪个？

### ISSUE THREAD

**Issue by zw0** [xiaonanln/goworld#60]
属性同步

> GoWorld为Entity提供了属性机制。属性分为服务端属性、客户端属性和全局属性。服务端属性只有在服务端可以访问，客户端属性可以在客户端和服务端同时访问。每次服务端对其进行修改的时候，属性的变化会立刻被同步到客户端，从而保持客户端数据的实时更新。全局属性是对所有Entity都可见的数据，包括其他玩家。全局属性在发生变化的时候会被广播到AOI范围内的所有玩家，从而使得玩家可以实时获取AOI范围内其他Entity的属性变化。

想学习一下实现

**Comment by xiaonanln** [comment]
代码不都在吗。

[https://github.com/xiaonanln/goworld/blob/master/engine/entity/MapAttr.go](https://github.com/xiaonanln/goworld/blob/master/engine/entity/MapAttr.go)
