### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by KonstantinKuklin** [xiaonanln/goworld#65]
As I understand you project correctly - it is a framework.
So you don't need to have the framework inside your own project, but here I found limitation: project source code should be inside the framework dir.
Example:
I created my project in ~/test/
I installed goworld framework, installed all deps. goworld with all deps stored in GOPATH, which is different as my project dir.
So when I want to build my test project I expect behavior like: goworld build ./test
But got: 
- goworld directory found: $GOPATH/src/github.com/xiaonanln/goworld
- server directory is $GOPATH/src/github.com/xiaonanln/goworld/test
Is that behavior is correct? Or what I did wrong?

Also to cheating that behavior I add symlink inside   $GOPATH/src/github.com/xiaonanln/goworld/test to my $HOME/test dir. Building\Starting processes fine, but on stopping - goworld can't find game instance and doesn't stop it and doesn't throw any error.

**Comment by xiaonanln** [comment]
- first of all, all Golang source code should be under $GOPATH
- This is the limitation of cmd/goworld, which assumes that server code is under  $GOPATH/src/github.com/xiaonanln/goworld/

**Comment by KonstantinKuklin** [comment]
yeah, it is.
But my project code may be anyware. 
But goworld expects to see my code inside $GOPATH/src/github.com/xiaonanln/goworld/ as well - this is a problem from my point of view

**Comment by xiaonanln** [comment]
you can still get goworld running without using cmd/goworld. 
just go build your ~/test
and also run dispatcher, gate manually

**Comment by KonstantinKuklin** [comment]
thx!
exactly what is needed
