### ISSUE TITLE
[unity demo]can not run multiple server

### ISSUE THREAD

**Issue by daniel840829** [xiaonanln/goworld#66]
I can not start unity demo server.
Here is my erro message
INFO[2018-04-12T14:23:44.264847348] Using config file: ~/go/src/github.com/xiaonanln/goworld/goworld.ini 
 > 1 dispatcher running, 0/1 gates running, 0/2 games () running
 >       22603     dispatcher      
~/go/src/github.com/xiaonanln/goworld/components/dispatcher/dispatcher
! server is already running, can not start multiple servers

**Comment by xiaonanln** [comment]
Somehow you have got a dispatcher process still running. 
You have to terminate the dispatcher process before starting servers
use `goworld stop examples/chatroom_demo` to kill the dispatcher process
