### ISSUE TITLE
官网邮件发送异常

### ISSUE THREAD

**Issue by gsw945** [xiaonanln/goworld#73]
### 官网 http://goworldgs.com/ 不能正常使用。
---
### 问题描述:
使用“Sign up”功能，提交时，出现下列错误提示信息:
> Oops! Something went wrong. Please reload the page and try again.

以为注册失败，用同样的信息再次注册时，提示账号已存在。
接着用刚才注册的账号"Sgin in", 登录成功。
看到提示
> We've sent a confirmation email to gsw945@*****. If it doesn't arrive soon, check your spam folder

检查了邮箱，并没有相关邮件。
于是，点击 ""Resend Confirmation Email"，依旧出现"Sign up"时出现的错误。
### 问题原因猜测:
疑似邮箱配置有误，导致注册时和重发验证邮件时都失败。

**Comment by simonlingoogle** [comment]
http://goworldgs.com is shutdown already.
