### ISSUE TITLE
如何让Dispatche分发到指定的Game?

### ISSUE THREAD

**Issue by github-yxb** [xiaonanln/goworld#78]
例如我想将不同的游戏业务分散在不同的game中，像Game-Hongjing,Game-Moshou,Dispatche根据不同的命令id分发到指定game

**Comment by xiaonanln** [comment]
客户端一旦连接gate，goworld就会在一个随机的game上创建一个Account对象，然后客户端和goworld之间才能开始真正的rpc通信。

你可以在Account里提供不同的rpc来让客户端迁移到不同的game（通过EnterSpace方法）。具体怎么找到对应的game和space，看你自己怎么实现。
