### ISSUE TITLE
請教分布式的一些問題

### ISSUE THREAD

**Issue by fnaith** [xiaonanln/goworld#91]
覺得這種架構挺精實的，很想導入現有專案，所以有些問題想請教。

1. 在這個架構中`不同的Game`指的就是`不同款遊戲`，這樣理解對嗎？

2. 在這個架構中`Space`可以理解成是`一個遊戲房間`嗎？

3. goworld-chatroom-demo 中的 [SendChat](https://github.com/xiaonanln/goworld-chatroom-demo-client/blob/master/assets/Script/GoWorld.js#L88) 呼叫的是 [SendChat_Client](https://github.com/xiaonanln/goworld/blob/9db2b0a30ca25960955ff4a86373cd4d22db7d87/examples/chatroom_demo/Avatar.go#L45) 嗎？ 怎麼註冊的？

4. entity 可以藉由 space 屬性對同一個 space 中的其他 entity 做廣播。那能廣播通知給所有同一個 game 的 entity 嗎？

5. 如果想啟動多個server / 掛ngnix跨機器 的話，有跨server的溝通方案嗎？

還請作者指點。

**Comment by xiaonanln** [comment]
> 1. 在這個架構中`不同的Game`指的就是`不同款遊戲`，這樣理解對嗎？

不同的`Game`是指不同的进程。Game进程是负责进行游戏逻辑处理的，都属于同一个游戏。多个Game的目的是为了把游戏的计算压力分到多个进程。

> 2. 在這個架構中`Space`可以理解成是`一個遊戲房間`嗎？

可以。需要注意的的是`Space`和它里面的所有`Entity`都是在同一个`Game`进程里。

> 3. goworld-chatroom-demo 中的 [SendChat](https://github.com/xiaonanln/goworld-chatroom-demo-client/blob/master/assets/Script/GoWorld.js#L88) 呼叫的是 [SendChat_Client](https://github.com/xiaonanln/goworld/blob/9db2b0a30ca25960955ff4a86373cd4d22db7d87/examples/chatroom_demo/Avatar.go#L45) 嗎？ 怎麼註冊的？

是的。这个注册过程是服务端自动的。

> 4. entity 可以藉由 space 屬性對同一個 space 中的其他 entity 做廣播。那能廣播通知給所有同一個 game 的 entity 嗎？

同一个`Space`里的所有`Entity`都在同一个进程，所以他们相互之间不需要进行通信，直接调用其他Entity的函数即可。所以如果你需要广播只要遍历`Space`里的所有`Entity`然后调用函数即可。

> 5. 如果想啟動多個server / 掛ngnix跨機器 的話，有跨server的溝通方案嗎？

只要设置好配置文件`goworld.ini`，然后启动多个`Game`, `Dispatcher`, `Gate`进程，他们之间就会自动相互连接形成一个集群。不需要Nginx。

**Comment by fnaith** [comment]
感謝您的回覆！很詳細啊，只有第5點`goworld.ini`的部分目前還懵懵懂懂，會再研究範例。
